### ISSUE TITLE
Server crash (unhandled exception)

### ISSUE THREAD

**Issue by vitaminx** [VanessaE/homedecor_modpack#205] opened 2015-03-02 14:41 UTC
Hi, I've updated homedecor from git yesterday and today I got a server crash (Debian Linux / minetest-server 0.4.11+repack-1):

    15:37:37: ERROR[main]: ERROR: An unhandled exception occurred: .../mods/homedecor_modpack/homedecor/handlers/expansion.lua:53: attempt to index local 'def' (a nil value) 
    15:37:37: ERROR[main]: stack traceback:
    15:37:37: ERROR[main]:  .../mods/homedecor_modpack/homedecor/handlers/expansion.lua:53: in function <.../mods/homedecor_modpack/homedecor/handlers/expansion.lua:51>

Thanks for fixing this.

Greetings, vitaminx

**Comment by kilbith** [comment] 2015-03-02 15:40
Can you provide the whole log before this crash please ? To see which action(s) have caused this.

**Comment by vitaminx** [comment] 2015-03-02 15:56
Here is the log file, It's quite big though:
http://files.callistix.net/minetest.log.gz

**Comment by kilbith** [comment] 2015-03-02 16:03
1. I did not asked for 88 MB of log, just the last actions before the crash.
2. I want to see the part in debug.txt, the file you gave me is wrong and I can't even see your crash into it.

**Comment by vitaminx** [comment] 2015-03-02 16:23
I don't have a debug.txt anywhere on the server, the minetest log level is set to 4 (verbose) - still I only get the minetest.log.
It's a bit strange because the verbose logs appear for some hours inside the minetest.log after server restart, but then suddenly they stop and I only get normal minetest logs. I've reported this already and it may be just another bug.
For the time being this is the only log I can provide.

**Comment by kilbith** [comment] 2015-03-02 16:30
Sorry, but $grep your crash returns nothing in your log. 

Moreover I notice that you report the same type of issue on the forum that I can't reproduce : https://forum.minetest.net/viewtopic.php?p=171543#p171543

Your server is not way up-to-date and your config probably not clean either.

**Comment by VanessaE** [comment] 2015-03-02 16:42
Then just tell me exactly what you did when it crashed, and provide the last screenful of text from the console, where this crash message came from.  Within it will be the rest of the stack traceback.  I'll need this info to find where the crash originated.

**Comment by vitaminx** [comment] 2015-03-02 16:46
I wan't connected when the server crashed, I can't say what action triggered it.
Here's the last bit of the log, but it contains no stack trace, although my minetest log level is set to "verbose":

    15:37:14: ACTION[ServerThread]: TugbaKayTugba joins game. List of players: Gordon1 Supergirlgamer schenlong GayMan arsefacey cyryl maki norman huner123 iwnis diegodavidcape domixd Arda cosmickoala pat30 zuzia883 TugbaKayTugba
    15:37:16: ACTION[ServerThread]: Player TugbaKayTugba moved too fast; resetting position
    15:37:16: ACTION[ServerThread]: CHAT: <domixd> ajd bar opisi
    15:37:16: ACTION[ServerThread]: killerjeff [190.87.239.28] joins game.
    15:37:16: ACTION[ServerThread]: killerjeff joins game. List of players: Gordon1 Supergirlgamer schenlong GayMan arsefacey cyryl maki norman huner123 iwnis diegodavidcape domixd Arda cosmickoala pat30 TugbaKayTugba zuzia883 killerjeff
    15:37:17: ACTION[ServerThread]: Supergirlgamer places node default:cobble at (-507,14,-342)
    15:37:20: ACTION[ServerThread]: Supergirlgamer places node default:cobble at (-503,14,-341)
    15:37:20: ACTION[ServerThread]: arsefacey places node default:cobble at (1096,-7178,-343)
    15:37:21: INFO[ServerThread]: arsefacey tried to place node in invalid position (1096,-7178,-343), replacing default:cobble
    15:37:22: ACTION[ServerThread]: Supergirlgamer places node default:cobble at (-503,14,-340)
    15:37:24: ACTION[ServerThread]: arsefacey places node default:cobble at (1096,-7177,-343)
    15:37:25: ACTION[ServerThread]: Supergirlgamer places node default:cobble at (-503,14,-339)
    15:37:27: ACTION[ServerThread]: Supergirlgamer places node default:cobble at (-503,14,-338)
    15:37:28: ACTION[ServerThread]: CHAT: <huner123> who wants unkown items
    15:37:28: ACTION[ServerThread]: TugbaKayTugba uses bucket:bucket_empty, pointing at [node under=-258,-84,-142 above=-258,-83,-142]
    15:37:28: ACTION[ServerThread]: GayMan tried to dig computer:monitor at protected position (-208,32,42)
    15:37:28: ACTION[ServerThread]: Supergirlgamer places node default:cobble at (-502,13,-336)
    15:37:30: ACTION[ServerThread]: TugbaKayTugba uses bucket:bucket_empty, pointing at [node under=-260,-83,-145 above=-259,-83,-145]
    15:37:30: ACTION[ServerThread]: Supergirlgamer places node default:cobble at (-503,14,-337)
    15:37:32: ACTION[ServerThread]: TugbaKayTugba uses bucket:bucket_empty, pointing at [node under=-260,-83,-143 above=-259,-83,-143]
    15:37:32: ACTION[ServerThread]: Supergirlgamer places node default:cobble at (-503,14,-336)
    15:37:34: ACTION[ServerThread]: TugbaKayTugba uses bucket:bucket_empty, pointing at [nothing]
    15:37:34: ACTION[ServerThread]: arsefacey places node default:cobble at (1097,-7180,-345)
    15:37:35: ACTION[ServerThread]: Supergirlgamer places node default:cobble at (-503,14,-335)
    15:37:37: ERROR[main]: ERROR: An unhandled exception occurred: .../mods/homedecor_modpack/homedecor/handlers/expansion.lua:53: attempt to index local 'def' (a nil value)
    15:37:37: ERROR[main]: stack traceback:
    15:37:37: ERROR[main]:  .../mods/homedecor_modpack/homedecor/handlers/expansion.lua:53: in function <.../mods/homedecor_modpack/homedecor/handlers/expansion.lua:51>

**Comment by t4im** [comment] 2015-03-03 17:03
>  \<huner123\> who wants unkown items

Unknown items are the usual suspects there… the common case of building against one is handled… but this apparently was caused by building an expanded homedecor item against something, which is hidden behind an unknown node in such a way that it would try to place the base where the unknown node was before.

Unless deployers where involved, i can't really explain how one manages to do that, but apparently someone did. I'll add some additional sanity checks against this.

**Comment by kilbith** [comment] 2015-03-03 17:12
I've tried to place an expanded homedecor item against the unknown items, in all situations nothing abnormal happens.

**Comment by t4im** [comment] 2015-03-03 17:31
Yes, the cases in which you would crash when placing against or on top of unknown nodes was fixed with the introduction of the expansion framework.

But this particular crash is the other way around:
When you would place against a known node placing it into the unknown node in front or over it. Usually an unknown node would make this impossible, because you cant point past it, but it seems someone managed this somehow anyway.

**Comment by t4im** [comment] 2015-03-03 17:45
You don't just have to build against an unknown node, but also into a second unknown node to cause this. As said, i have no idea how to actually do or test this though.

**Comment by t4im** [comment] 2015-03-03 17:51
Finally found out how:
With protection active you can dig one unknown node, and place against the second unknown. The protection will keep the first one in place leading to this crash.
You can use [mtt mod_test's](https://github.com/t4im/mtt) `/protect on` command to validate this.

**Closed** 2015-03-04 01:06 UTC
